import { colorWarning } from "./utils";
import semver from "semver";
import hardhatPkg from "hardhat/package.json";

// Try to check if hardhat version is compatible
if (
  semver.lt(hardhatPkg.version, "2.22.5") ||
  semver.gte(hardhatPkg.version, "3.0.0")
) {
  console.warn(
    colorWarning(`
WARNING from "hardhat-tracer" plugin

This message is generated by plugin "hardhat-tracer" because it is
dependent on some features available in hardhat >=2.22.5 <3.0.0.

Please upgrade your hardhat version to 2.22.5 or above.

npm i hardhat@latest

or

yarn add hardhat@latest
        `)
  );
}

import "./chai";
import "./extend";
import "./tasks";
export * from "./types";
export * from "./wrapper";
